_security_logout:
    resource: security.route_loader.logout
    type: service

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [GET, POST]

app_register:
    path: /register
    controller: App\Controller\SecurityController::register
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout
    methods: [GET, POST]
